import 'package:flutter/material.dart';

class TaskIcons {
  static const _keywordMap = <String, String>{
    'okul': 'school',
    'ödev': 'school',
    'ders': 'school',
    'study': 'school',
    'school': 'school',
    'read': 'menu_book',
    'oku': 'menu_book',
    'kitap': 'menu_book',
    'iş': 'work',
    'toplantı': 'groups',
    'meeting': 'groups',
    'work': 'work',
    'ofis': 'work',
    'spor': 'fitness',
    'egzersiz': 'fitness',
    'gym': 'fitness',
    'fitness': 'fitness',
    'koş': 'directions_run',
    'run': 'directions_run',
    'yürü': 'directions_walk',
    'walk': 'directions_walk',
    'yemek': 'restaurant',
    'cook': 'restaurant',
    'mutfak': 'restaurant',
    'kahvaltı': 'free_breakfast',
    'breakfast': 'free_breakfast',
    'temiz': 'cleaning',
    'clean': 'cleaning',
    'alışveriş': 'shopping',
    'shop': 'shopping',
    'market': 'shopping',
    'sağlık': 'health',
    'health': 'health',
    'doktor': 'health',
    'ilaç': 'medication',
    'müzik': 'music',
    'music': 'music',
    'kod': 'code',
    'code': 'code',
    'program': 'code',
    'yazılım': 'code',
    'email': 'email',
    'mail': 'email',
    'e-posta': 'email',
    'uyku': 'bedtime',
    'sleep': 'bedtime',
    'medit': 'self_improvement',
    'yoga': 'self_improvement',
    'odak': 'timer',
    'focus': 'timer',
    'proje': 'lightbulb',
    'project': 'lightbulb',
    'sunum': 'slideshow',
    'presentation': 'slideshow',
    'araştır': 'search',
    'research': 'search',
    'video': 'videocam',
    'film': 'movie',
    'çiz': 'brush',
    'draw': 'brush',
    'design': 'brush',
    'tasarım': 'brush',
    'araba': 'directions_car',
    'drive': 'directions_car',
    'seyahat': 'flight',
    'travel': 'flight',
    'uçak': 'flight',
    'çocuk': 'child_care',
    'baby': 'child_care',
    'pet': 'pets',
    'köpek': 'pets',
    'kedi': 'pets',
    'bahçe': 'yard',
    'garden': 'yard',
    'su': 'water_drop',
    'water': 'water_drop',
    'kahve': 'coffee',
    'coffee': 'coffee',
    'çay': 'coffee',
  };

  static const _iconData = <String, IconData>{
    'task': Icons.task_alt_rounded,
    'school': Icons.school_rounded,
    'menu_book': Icons.menu_book_rounded,
    'work': Icons.work_rounded,
    'groups': Icons.groups_rounded,
    'fitness': Icons.fitness_center_rounded,
    'directions_run': Icons.directions_run_rounded,
    'directions_walk': Icons.directions_walk_rounded,
    'restaurant': Icons.restaurant_rounded,
    'free_breakfast': Icons.free_breakfast_rounded,
    'cleaning': Icons.cleaning_services_rounded,
    'shopping': Icons.shopping_bag_rounded,
    'health': Icons.health_and_safety_rounded,
    'medication': Icons.medication_rounded,
    'music': Icons.music_note_rounded,
    'code': Icons.code_rounded,
    'email': Icons.email_rounded,
    'bedtime': Icons.bedtime_rounded,
    'self_improvement': Icons.self_improvement_rounded,
    'timer': Icons.timer_rounded,
    'lightbulb': Icons.lightbulb_rounded,
    'slideshow': Icons.slideshow_rounded,
    'search': Icons.search_rounded,
    'videocam': Icons.videocam_rounded,
    'movie': Icons.movie_rounded,
    'brush': Icons.brush_rounded,
    'directions_car': Icons.directions_car_rounded,
    'flight': Icons.flight_rounded,
    'child_care': Icons.child_care_rounded,
    'pets': Icons.pets_rounded,
    'yard': Icons.yard_rounded,
    'water_drop': Icons.water_drop_rounded,
    'coffee': Icons.coffee_rounded,
  };

  static String inferName(String title) {
    final lower = title.toLowerCase();
    for (final entry in _keywordMap.entries) {
      if (lower.contains(entry.key)) return entry.value;
    }
    return 'task';
  }

  static IconData iconForTask({required String title, required String icon}) {
    final name = icon == 'task' ? inferName(title) : icon;
    return _iconData[name] ?? Icons.task_alt_rounded;
  }

  static IconData fromName(String name) => _iconData[name] ?? Icons.task_alt_rounded;
}
